### ISSUE TITLE
Сompatibility with region-specific executables

### ISSUE THREAD

**Issue by AlSar163** [ExOptsTeam/NFSUExOpts#11]
Hello, _**nlgzrgn**_ and other _**ExOpts Team**_ members!

Thank you for your great and invaluable work on classic NFS titles!
I usually use ExtraOptions scripts without any difficulties
but recently ran into a problem with _NFSU Extra Options_. 

In the Readme you mention the support of _v1.4 speed.exe (3,03 MB (3.178.496 bytes))_
and advise to search for _NFS Underground v1.4 NO CD Crack DRUNK!_.
As far as I understood, according to **gamecopyworld** database, by above statements
you mean the support of _**v1.4 US No-CD**_ executable (by DEViANCE).

The problem is that US-regional executable can't be used properly
with EU-regional releases due to different file structure of cutscenes etc.
Personally, I'm using official Russian release of NFSU (v1.4 by SoftClub)
and always get either a black screen or a flickering freeze with US EXE.

If I try to use EU-regional executable, namely _**v1.4 EU No-CD**_ (by SPiRiTY)
which has the same size of 3.178.496 bytes (3,03 MB) as you requested
I can launch the game at least but ExOpts suffer from reduced functionality.
E.g. _UnlockAllThings_, _AutoDrive_ and _FreezeCamera_ don't work at all.
_RacerControllers_ displays its option but regardless of choice there are always 4 opponents. 
However, all the other options seem to work fine and as intended.

When I try to use RU-regional executable which is _**v1.4 RU No-CD**_ (by Z0oMiK)
it has slightly different size of 3.183.036 bytes (3,03 MB) and ExOpts doesn't start
at all displaying promt that "This .exe is not supported".

EU EXE renders the game to work in English with occasional text coding errors like _**Óèêèïåäèÿ**_.
Russian localization seems to be EXE-dependent as registry settings remain the same
(HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\EA GAMES\NFS Underground\)
with Language=Russian and Locale=ru and language file replacement result in complete "_**Óèêèïåäèÿ**_".

As I prefer to use the localized version, I can't make it work with ExOpts by any means.
I tried using ExOpts features _ShowLanguageSelectScreen_ and _GameRegion_.
The former results in game crash after trying to select anything other than English.
The latter doesn't affect localization in any way regardless of used number.
Meanwhile other popular script named _NFSU WS Fix_ (by ThirteenAG) works fine with all EXE's.
Also, _NFSMW ExOpts_ works as intended with both EU and RU executables of MW respectively.

So my questions or requests are the following:
1) Is it possible to make EU EXE fully compatible with ExOpts?
This EXE can be found on **gamecopyworld** by the name
_NFS: Underground v1.4 [EURO] No-CD/Fixed EXE_
2) Is it possible to make RU EXE compatible with ExOpts?
At least partially just like EU EXE is currently working...
This EXE can be found on **gamecopyworld** by the name
_NFS: Underground - SoftClub v1.4.0 [RUSSIAN] No-CD/Fixed EXE_

Thank you for your attention in advance!
Best wishes, AlSar.

P.S. And of course I maybe doing something wrong. Perhaps I can find some
Russian compatriots here or other competent people who can point out my mistakes.

**Comment by nlgxzef** [comment]
Hi and thanks for the wall of text. Unfortunately, Extra Options is only developed for the most common versions of the games. It's easier for you to get US version instead of us doing everything from zero to support specific versions.
Sorry for that.

Closed.

**Comment by AlSar163** [comment]
Hi, nlgxzef!
I'll remember your new nickname =)

Thank you for the quick response. Of course I understand that the amount of work
on Extra Options is huge. If it's not a simple task to adapt ExOpts for other EXEs
than I fully understand that you decided to focus on only one specific version.

I'll try to figure out how to combine US executable with
Russian EU release and possibly even with the localization.

Thank you once again for your great work.
Regards, AlSar.
